import type { Metadata } from 'next'
import { ClerkProvider } from '@clerk/nextjs'
import { Inter } from 'next/font/google'
import { ThemeProvider } from '@/components/theme-provider'
import './globals.css'
import AuthProviders from '@/providers/AuthProvider'
import { ReduxProvider } from '@/redux/ReduxProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <AuthProviders>
      <html lang='en'>
        <ReduxProvider>
          <body className={inter.className}>
            <ThemeProvider attribute='class' storageKey='streaming'>
              {children}
            </ThemeProvider>
          </body>
        </ReduxProvider>
      </html>
    </AuthProviders>
  )
}
